### ISSUE TITLE
use camunda rule in BeforeScenario

### ISSUE THREAD

**Issue by jangalinski** [holunda-io/camunda-bpm-jgiven#1]
When the Test extends ScenarioTest and defines a camunda ProcessEngineRule
then in the @BeforeScenario method of a stage
the process engine rule is null.

This does not allow us to register deployments in the beforeScenario lifecycle method.

Desired behaviour: camunda rule is initialized.

Possible Solution JGiven/Camunda RuleChain.

**Comment by zambrovski** [comment]
Probably won't be implemented - there are workarounds for this and for now we also support JUnit5
