### ISSUE TITLE
fix transitive dependencies 

### ISSUE THREAD

**Issue by jangalinski** [holunda-io/camunda-bpm-jgiven#121]
We ran into a problem today where a jgiven process test did not work and we couldn't easily find out why. Turned out we where not using the `junit5/DualScenarioTest` (v 1.2.2) as we thought, but `junit/DualScenarioTest` (v 1.2.0) ... which comes via this extension lib (v 0.2.0).

jgiven does a good job to separate modules so I can pick what I need (junit5 + spring has no deps on junit4).  But when I use camunda-bpm-jgiven, I get everything that jgiven provides ... html report, spring, both junits ....

Instead we should either:

only keep the minimal (jgiven-core) dependencies we need to write the stages and leave wiring to the user

provide separate libs for junit4, junit5, ....

I'd prefer Option 1. Especially since the pom contains the hint: `<!-- This is a test library not a BOM, trying to avoid transitive dependencies -->`.

**Comment by zambrovski** [comment]
after fixing and releasing the stuff like it is, I'll address this issue.
